### ISSUE TITLE
Captured media in stdout

### ISSUE THREAD

**Issue by ceuk** [orhun/menyoki#10]
Hey - is it possible to output the captured buffer so you can pipe it to other commands (e.g. `xclip`)

Related: is there an existing way to copy a capture to the clipboard?

Cheers

**Comment by orhun** [comment]
Hey, you can use `"-"` as an argument to `save` subcommand with the upcoming release for redirecting output to stdout. Or if you don't want to wait, build menyoki yourself and try it :)

Some use cases:

```sh
menyoki -q cap jpg -q 100 save - > "hq_img.jpg" # redirect output to hq_img.jpg
menyoki -q cap png save - | 0x0 - # paste it to https://0x0.st/
```

**Comment by ceuk** [comment]
awesome, cheers!

**Comment by MonAaraj** [comment]
Sorry to revive such an old issue, but won't it be a good idea to include such a command in the examples in the README.md? I believe it might help a lot of beginners.

**Comment by orhun** [comment]
> Sorry to revive such an old issue, but won't it be a good idea to include such a command in the examples in the README.md? I believe it might help a lot of beginners.

Yeah, that makes sense. I guess I didn't want to include previous examples in README.md because at least one of them was specific about 0x0 (or I just forgot to do it :D)

Interested in submitting a PR?

**Comment by MonAaraj** [comment]
Sorry for the late response, and yes! I've just forked your project and committed it, I'll be setting it up
