### ISSUE TITLE
Menyoki is unable to capture screen on QubesOS

### ISSUE THREAD

**Issue by Kreyren** [orhun/menyoki#13]
```console
user@personal:~$ menyoki record gif --fps 10
[2020-12-09T00:20:45 INFO menyoki::x11::display] 
 Window title  -> "(?)"
 Window size   -> [1x1]
[2020-12-09T00:20:45 ERROR menyoki::x11] BadMatch (invalid parameter attributes) [Opcode: 61, Serial: 19]
Selected area -> [1x1] 
...
```

### Steps to reproduce
1. Get QubesOS R4.1 (most likely reproducible on R4.0 as well)
2. Create a new VM based on debian-11
3. In VM install package `librust-x11-dev` to avoid build failure (https://github.com/orhun/menyoki/issues/7)
4. In VM install `cargo` to get rustlang backend
5. In VM Run `cargo install menyoki`
6. In VM Run `menyoki record gif --fps 10` and expect failure highlighted above.

#### Works on Flameshot
Using alternative `flameshot` called as `flameshot gui` works.

#### Effects of qubes-issues/6271
Might be affected by https://github.com/QubesOS/qubes-issues/issues/6271

**Comment by orhun** [comment]
Can you test if the latest release fixed this issue?

**Comment by Kreyren** [comment]
@orhun That seems to fix it! Thanku ^-^

```console
user@menyoki:~$ ~/.cargo/bin/menyoki -V
menyoki 1.1.0
user@menyoki:~$ ~/.cargo/bin/menyoki record gif --fps 10
[2020-12-11T01:49:38 INFO menyoki::x11::display] 
 Window title  -> "user@menyoki: ~"
 Window size   -> [995x639]
^Celected area -> [995x639] 
```
