### ISSUE TITLE
Capture single screen

### ISSUE THREAD

**Issue by anihm136** [orhun/menyoki#15]
**Is your feature request related to a problem? Please describe.**
I use a dual monitor setup, and sometimes I would like to capture the whole of a single monitor. Currently it is possible by specifying `--root --select` and adjusting the selection to one monitor, but it would be nice to have an option to directly select a monitor

**Describe the solution you'd like**
A flag to select a monitor, preferably by screen id (or any other convenient way to reference a screen)

**Describe alternatives you've considered**
As mentioned above, the flags can be used to eventually capture a single screen. It may be possible to write a script to compute the appropriate parameters to capture one screen, but if it is feasible a flag would be preferable

**Comment by orhun** [comment]
Hey,
You'll be able to specify the <s>screen</s> monitor via `--monitor <NUM>` argument for **record**/**capture** actions with the upcoming release. (Handled via [RandR extension](https://www.x.org/releases/X11R7.5/doc/man/man1/xrandr.1.html)).

You can build menyoki from source and test it out if you don't want to wait for the next release. In fact, that'd be great for spotting the bugs in advance if there's any :)

Thanks for the submission!

**Comment by anihm136** [comment]
I'll try it out and let you know if I face any issues. And thank _you_ for the excellent software!

**Comment by anihm136** [comment]
The feature is working fine as documented. One small issue, not sure if its related or not. When I capture the root window with `menyoki capture --root` (along with any other parameters, such as `--select` or `--select --monitor 1`), the green border showing the selection area does not show up anymore. The correct dimensions are shown on the terminal, and the capture also works properly, its just the outline that is not visible. The border appears when capturing a non-root window.
I ran the test suite, and noticed that two tests are failing on my system. The full results are below. I use two monitors in a side-by-side configuration, one is 1920x1080 and the other is 1366x768.
<details>
➜ cargo test --features test-ws
    Finished test [optimized + debuginfo] target(s) in 0.06s
     Running target/debug/deps/menyoki-b35f562e2f18c344

running 36 tests
test analyze::settings::tests::test_time_zone ... ok
test anim::decoder::tests::test_anim_decoder ... ok
test analyze::settings::tests::test_analyze_settings ... ok
test anim::tests::test_anim_mode ... ok
test anim::settings::tests::test_split_settings ... ok
test args::parser::tests::test_parser ... ok
test apng::tests::test_apng_encoder ... ok
test args::matches::tests::test_matches ... ok
test edit::settings::tests::test_edit_settings ... ok
test analyze::tests::test_analyze ... ok
test gif::encoder::tests::test_gif_encoder ... ok
test anim::settings::tests::test_anim_settings ... ok
test image::geometry::tests::test_geometry ... ok
test image::padding::tests::test_padding ... ok
test file::settings::tests::test_save_settings ... ok
test image::settings::tests::test_jpg_settings ... ok
test image::settings::tests::test_png_settings ... ok
test file::tests::test_file ... ok
test image::tests::test_image ... ok
test record::settings::tests::test_record_settings ... ok
test args::tests::test_shell_completions ... ok
test app::tests::test_app_image ... ok
test settings::tests::test_app_settings ... ok
test image::settings::tests::test_pnm_settings ... ok
test gif::encoder::tests::test_gifski_encoder ... ok
test util::logger::tests::test_logger ... ok
test util::state::tests::test_input_state ... ok
test util::keys::tests::test_action_keys ... ok
test util::command::tests::test_command ... ok
test record::fps::tests::test_fps ... ok
test edit::tests::test_edit ... ok
test app::tests::test_app_anim ... ok
test record::tests::test_record ... ok
test x11::display::tests::test_x11_display ... ok
test x11::window::tests::test_x11_window ... FAILED
test x11::tests::test_x11_system ... FAILED

failures:

---- x11::window::tests::test_x11_window stdout ----
thread 'x11::window::tests::test_x11_window' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 Geometry {
<    x: 0,
>    x: 1366,
     y: 0,
<    width: 1366,
<    height: 768,
>    width: 1920,
>    height: 1080,
 }

', src/x11/window.rs:492:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- x11::tests::test_x11_system stdout ----
thread 'x11::tests::test_x11_system' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<3147264
>10646640

', src/x11/mod.rs:149:9


failures:
    x11::tests::test_x11_system
    x11::window::tests::test_x11_window

test result: FAILED. 34 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.70s

error: test failed, to rerun pass '--bin menyoki'
</details>
Let me know if I can provide any other details. If you prefer me to open a new issue for this let me know as well

**Comment by orhun** [comment]
Hmm, that's unexpected. Can you increase the border width (`e.g. --border 10`) and see if shows up?

Failing tests are expected though. I used hardcoded values for the window dimensions. (They are meant to be run with `xvfb`, e.g. `xvfb-run --server-args="-screen 0 1366x768x24" cargo test --features test-ws`)

**Comment by anihm136** [comment]
Okay, the tests work with `xvfb-run`. But setting border width to 10 did not change anything, still shows the right thing on terminal but no border on screen

**Comment by anihm136** [comment]
Huh. That's odd. I was sure that it was working correctly with the released version (1.1.0), but checking now it seems to not show up even on that version

**Comment by orhun** [comment]
That's weird. Did restarting X11 help?

**Comment by anihm136** [comment]
Nope. Just tried that too

**Comment by orhun** [comment]
I'm trying to reproduce the issue and realized that borders are not visible at the start but they become visible when I move/resize them on my 1920x1080 monitor. Everything's fine on my other monitor. Maybe it's trying to draw them outside the screen boundaries. Can you confirm that if that's your issue or not?

**Comment by anihm136** [comment]
Yes, the area size is seen correctly. However, the borders are definitely not seen at all. I verified this by doing `menyoki capture --root --select --size $(slop)`, and selected a region in the middle of my screen. No borders show up

**Comment by orhun** [comment]
It looks like it's time that I investigate this problem in a separate issue. Can you create a [new issue](https://github.com/orhun/menyoki/issues/new?assignees=orhun&labels=bug&template=bug_report.md&title=Borders%20are%20not%20visible) where you provide the information about your system (OS, WM, X version, logs etc.) after closing this one?

**Comment by anihm136** [comment]
Cool. I've opened #16 to discuss this further
