### ISSUE TITLE
Borders are not visible

### ISSUE THREAD

**Issue by anihm136** [orhun/menyoki#16]
**Describe the bug**
When starting a record/capture on the root window, the borders of the capture area are not visible. The selected area correctly shows up in the terminal, and completing the capture also saves the correct image (as per the selection shown in terminal)

**To Reproduce**
1. Run `menyoki capture --root --select`
2. Try resizing the capture area
3. The new dimensions are seen on the terminal, but the border cannot be seen

**Expected behavior**
The borders of the capture area should be seen even on the root window

**Screenshots/Logs**
N/A

**System Information**
 - OS: Linux 5.4.0-58-generic Ubuntu 20.04 x86_64
 - Rust Version: 1.50.0-nightly
 - Project Version: 1.1.0
 - X server version: 2:1.20.8-2ubuntu2.6
 - WM: awesomeWM 4.3

**Additional context**
Previous discussion [here](https://github.com/orhun/menyoki/issues/15)

**Comment by orhun** [comment]
Still having the same problem?
