### ISSUE TITLE
Changing keybindings for cancel operation

### ISSUE THREAD

**Issue by Poroing** [orhun/menyoki#22]
I just found out about menyoki and find it great as it allows me to record my computer enterily through the keyboard.

Since I'm often hitting the `Escape` key when using the softwares installed on my computer, I would like to change the keybinding for the cancel action. However, I couldn't find any information on how to so in the man pages of both the configuration and the command.

Is it possible to change the keybindings for the key other than the action key ? Especially the cancel key ?
If not, would this be implemented in the future ?

**Comment by orhun** [comment]
Hello, thanks for reporting this!

Unfortunately it's not possible to change the _cancel keys_ for now. But I'm thinking of implementing the following arguments in the future:

```
--action-keys <KEYS>          Set the action keys [default: LAlt-S/Enter]
--cancel-keys <KEYS>          Set the cancel keys [default: Esc]
```

**Comment by orhun** [comment]
It will be possible to change the key bindings for the cancel operation via `--cancel-keys` with the upcoming release.

**Comment by Poroing** [comment]
Great ! Thank you.
