### ISSUE TITLE
Cancelling record or capture aborts

### ISSUE THREAD

**Issue by nabijaczleweli** [orhun/menyoki#3]
**Describe the bug**
```
[2020-12-02T15:58:54 WARN menyoki::x11::display] User interrupt detected.
thread 'main' panicked at 'Failed to get the window', src/app.rs:169:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped, if enabled)
```

**To Reproduce**
`menyoki capture` then Esc

**Expected behavior**
Not doing that; something to the effect of `let window = self.window?;` instead or the equivalent where it's assigned, probably.

**System Information**
 - OS: buster and sid
 - Rust Version: rustc 1.48.0 (7eac88abb 2020-11-16)
 - Project Version: e2f596b66c182ca1e93421a332858d392a818faf

**Comment by orhun** [comment]
Please check if 09ef590a3e8954501f6d2d7097a3e05c3ccd7ce2 fixes this.
Also I'm open if you want to suggest anything about refactoring the code etc.

**Comment by nabijaczleweli** [comment]
Yep, that works
