### ISSUE TITLE
Expand shell expressions for files

### ISSUE THREAD

**Issue by orhun** [orhun/menyoki#39]
**Is your feature request related to a problem? Please describe.**

Shell expressions are not expanded for input/output files.

```
$ menyoki edit "~/test.png"
[2023-05-10T19:50:30 ERROR menyoki] IO error: `No such file or directory (os error 2)`
```

**Describe the solution you'd like**

Use a crate such as [`shellexpand`](https://gitlab.com/ijackson/rust-shellexpand) to handle these cases.

e.g. `~/test.png` should be expanded as `/home/orhun/test.png`

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by JerelJr** [comment]
I would like to try my hand at this issue if it is not being worked on.

**Comment by orhun** [comment]
Go ahead!
