### ISSUE TITLE
The duration argument (-d <S>) doesn't seem to work

### ISSUE THREAD

**Issue by yurivict** [orhun/menyoki#50]
**Describe the bug**
I expected this command to record for 10 seconds and exit, but it didn't exit:
```
menyoki record -d 10 gif --fps 30 -s save x.gif
```

**System Information**
 - OS: FreeBSD 14.0
 - Rust Version: 1.74.1
 - Project Version: 1.7.0

**Comment by orhun** [comment]
I am unable to reproduce this. Did you get the related log message when you run the command?

```
[2024-01-11T21:32:17 INFO menyoki::record] Recording 30 FPS for 10 seconds...
```

**Comment by yurivict** [comment]
No, it starts, prints the following, and then doesn't do anyting else.

```
$ menyoki record -d 10 gif --fps 30 -s save x.gif
[2024-01-11T10:51:27 INFO menyoki::x11::display] 
 Window title  -> "menyoki : bash"
 Window size   -> [3840x2109]
 Selected area -> [3840x2109] 
```

**Comment by orhun** [comment]
You need to select the window to start recording (`Alt + S`). Or you can do this to record the root window (fullscreen):

```sh
menyoki record --root -d 10 gif --fps 30 -s save x.gif
```

**Comment by orhun** [comment]
Hey, is there any updates? 👀

**Comment by orhun** [comment]
Let me know if you're still having this issue.
