### ISSUE TITLE
Ctrl+c does not work to stop during the saving of the gif.

### ISSUE THREAD

**Issue by pythops** [orhun/menyoki#52]
**Describe the bug**
When the gif is being saved, pressing `ctrl +c` to cancel it, does not have any effect.
```
[2024-02-02T13:42:06 INFO menyoki::gif] Saving... (30%)
```
This is an issue when there is a long capture that we want to cancel anyway.

**To Reproduce**
1. Run a capture 
2. stop the capture
3. try to interrupt the saving process.

**Expected behavior**
The saving process should be stopped.

**System Information**
 - OS: [Arch Linux]
 - Project Version: [1.7.0]

**Comment by orhun** [comment]
It is because ctrl-c is not a cancel key as default. You could try ctrl-d instead.

CLI is a bit awkard (#44) so it might be better to document this and #53 

What do you think?

**Comment by pythops** [comment]
okay, did not know that.
maybe the basic usage key bindings can be made more clear in the documentation.
